# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "addbe2d55db106bd399d5ed3905fc275"
name = "growing-projection-app"
handle = "growing-projection-app-6"
application_url = "https://informal-delivered-climate-mailed.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://informal-delivered-climate-mailed.trycloudflare.com/auth/callback",
  "https://informal-delivered-climate-mailed.trycloudflare.com/auth/shopify/callback",
  "https://informal-delivered-climate-mailed.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[app_proxy]
url = "https://informal-delivered-climate-mailed.trycloudflare.com"
prefix = "apps"
subpath = "bundle"
